// <auto-generated />
using System;
using ECL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ECL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260509064006_AddStudentProgress")]
    partial class AddStudentProgress
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ECL.Models.GrammarQuestion", b =>
                {
                    b.Property<int>("Qno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("qno");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Qno"));

                    b.Property<int>("CorrectOption")
                        .HasColumnType("integer")
                        .HasColumnName("correctoption");

                    b.Property<string>("Explanation")
                        .HasColumnType("text")
                        .HasColumnName("explanation");

                    b.Property<string>("GrammarType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("grammartype");

                    b.Property<string>("Level")
                        .HasColumnType("text")
                        .HasColumnName("level");

                    b.Property<string>("OptionA")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("optiona");

                    b.Property<string>("OptionB")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("optionb");

                    b.Property<string>("OptionC")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("optionc");

                    b.Property<string>("OptionD")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("optiond");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("questiontext");

                    b.HasKey("Qno");

                    b.ToTable("grammarquestions", "public");
                });

            modelBuilder.Entity("ECL.Models.ListeningQuestion", b =>
                {
                    b.Property<int>("Qno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("qno");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Qno"));

                    b.Property<string>("AudioFile")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("audiofile");

                    b.Property<int>("CorrectOption")
                        .HasColumnType("integer")
                        .HasColumnName("correctoption");

                    b.Property<int>("FormNumber")
                        .HasColumnType("integer")
                        .HasColumnName("formnumber");

                    b.Property<string>("OptionA")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("optiona");

                    b.Property<string>("OptionB")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("optionb");

                    b.Property<string>("OptionC")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("optionc");

                    b.Property<string>("OptionD")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("optiond");

                    b.HasKey("Qno");

                    b.ToTable("listeningquestions", "public");
                });

            modelBuilder.Entity("ECL.Models.QuizAttempt", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("CorrectCount")
                        .HasColumnType("integer")
                        .HasColumnName("correctcount");

                    b.Property<DateTime?>("FinishedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finishedatutc");

                    b.Property<int?>("FormNumber")
                        .HasColumnType("integer")
                        .HasColumnName("formnumber");

                    b.Property<string>("GrammarType")
                        .HasColumnType("text")
                        .HasColumnName("grammartype");

                    b.Property<string>("Level")
                        .HasColumnType("text")
                        .HasColumnName("level");

                    b.Property<int>("Mode")
                        .HasColumnType("integer")
                        .HasColumnName("mode");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("startedatutc");

                    b.Property<int>("StudentUserId")
                        .HasColumnType("integer")
                        .HasColumnName("studentuserid");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("integer")
                        .HasColumnName("totalquestions");

                    b.HasKey("Id");

                    b.HasIndex("StudentUserId");

                    b.ToTable("quizattempts", "public");
                });

            modelBuilder.Entity("ECL.Models.QuizAttemptAnswer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("CorrectOption")
                        .HasColumnType("integer")
                        .HasColumnName("correctoption");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean")
                        .HasColumnName("iscorrect");

                    b.Property<int>("Mode")
                        .HasColumnType("integer")
                        .HasColumnName("mode");

                    b.Property<int>("QuestionQno")
                        .HasColumnType("integer")
                        .HasColumnName("questionqno");

                    b.Property<long>("QuizAttemptId")
                        .HasColumnType("bigint")
                        .HasColumnName("quizattemptid");

                    b.Property<int?>("SelectedOption")
                        .HasColumnType("integer")
                        .HasColumnName("selectedoption");

                    b.HasKey("Id");

                    b.HasIndex("QuizAttemptId", "QuestionQno")
                        .IsUnique();

                    b.ToTable("quizattemptanswers", "public");
                });

            modelBuilder.Entity("ECL.Models.ReadingQuestion", b =>
                {
                    b.Property<int>("Qno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("qno");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Qno"));

                    b.Property<int>("CorrectOption")
                        .HasColumnType("integer")
                        .HasColumnName("correctoption");

                    b.Property<int>("FormNumber")
                        .HasColumnType("integer")
                        .HasColumnName("formnumber");

                    b.Property<string>("OptionA")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("optiona");

                    b.Property<string>("OptionB")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("optionb");

                    b.Property<string>("OptionC")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("optionc");

                    b.Property<string>("OptionD")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("optiond");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("questiontext");

                    b.HasKey("Qno");

                    b.ToTable("readingquestions", "public");
                });

            modelBuilder.Entity("ECL.Models.StudentUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdatutc");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("passwordhash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("studentusers", "public");
                });

            modelBuilder.Entity("ECL.Models.QuizAttempt", b =>
                {
                    b.HasOne("ECL.Models.StudentUser", "StudentUser")
                        .WithMany()
                        .HasForeignKey("StudentUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudentUser");
                });

            modelBuilder.Entity("ECL.Models.QuizAttemptAnswer", b =>
                {
                    b.HasOne("ECL.Models.QuizAttempt", "QuizAttempt")
                        .WithMany("Answers")
                        .HasForeignKey("QuizAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuizAttempt");
                });

            modelBuilder.Entity("ECL.Models.QuizAttempt", b =>
                {
                    b.Navigation("Answers");
                });
#pragma warning restore 612, 618
        }
    }
}
