using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ECL.Migrations
{
    /// <inheritdoc />
    public partial class AddGrammarQuestions : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // The repo contains an external SQL questionbank that may create this table manually.
            // Use IF NOT EXISTS so the migration is safe on existing databases.
            migrationBuilder.Sql(
                """
                CREATE SCHEMA IF NOT EXISTS public;

                CREATE TABLE IF NOT EXISTS public.grammarquestions (
                    qno integer GENERATED BY DEFAULT AS IDENTITY,
                    grammartype text NOT NULL,
                    questiontext text NOT NULL,
                    optiona text NOT NULL,
                    optionb text NOT NULL,
                    optionc text NOT NULL,
                    optiond text NOT NULL,
                    correctoption integer NOT NULL,
                    CONSTRAINT "PK_grammarquestions" PRIMARY KEY (qno)
                );
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                DROP TABLE IF EXISTS public.grammarquestions;
                """);
        }
    }
}
