// <auto-generated />
using ECL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ECL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260508194338_AddGrammarQuestions")]
    partial class AddGrammarQuestions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ECL.Models.GrammarQuestion", b =>
                {
                    b.Property<int>("Qno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("qno");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Qno"));

                    b.Property<int>("CorrectOption")
                        .HasColumnType("integer")
                        .HasColumnName("correctoption");

                    b.Property<string>("GrammarType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("grammartype");

                    b.Property<string>("OptionA")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("optiona");

                    b.Property<string>("OptionB")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("optionb");

                    b.Property<string>("OptionC")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("optionc");

                    b.Property<string>("OptionD")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("optiond");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("questiontext");

                    b.HasKey("Qno");

                    b.ToTable("grammarquestions", "public");
                });

            modelBuilder.Entity("ECL.Models.ListeningQuestion", b =>
                {
                    b.Property<int>("Qno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("qno");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Qno"));

                    b.Property<string>("AudioFile")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("audiofile");

                    b.Property<int>("CorrectOption")
                        .HasColumnType("integer")
                        .HasColumnName("correctoption");

                    b.Property<int>("FormNumber")
                        .HasColumnType("integer")
                        .HasColumnName("formnumber");

                    b.Property<string>("OptionA")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("optiona");

                    b.Property<string>("OptionB")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("optionb");

                    b.Property<string>("OptionC")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("optionc");

                    b.Property<string>("OptionD")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("optiond");

                    b.HasKey("Qno");

                    b.ToTable("listeningquestions", "public");
                });

            modelBuilder.Entity("ECL.Models.ReadingQuestion", b =>
                {
                    b.Property<int>("Qno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("qno");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Qno"));

                    b.Property<int>("CorrectOption")
                        .HasColumnType("integer")
                        .HasColumnName("correctoption");

                    b.Property<int>("FormNumber")
                        .HasColumnType("integer")
                        .HasColumnName("formnumber");

                    b.Property<string>("OptionA")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("optiona");

                    b.Property<string>("OptionB")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("optionb");

                    b.Property<string>("OptionC")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("optionc");

                    b.Property<string>("OptionD")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("optiond");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("questiontext");

                    b.HasKey("Qno");

                    b.ToTable("readingquestions", "public");
                });
#pragma warning restore 612, 618
        }
    }
}
