-- ============================================
-- ENGLISH GRAMMAR QUESTION BANK
-- 1000+ QUESTIONS WITH 30+ PER GRAMMAR TYPE
-- ============================================

-- 1. TENSES (Present, Past, Future) - 60 questions
INSERT INTO public.grammarquestions (GrammarType, questiontext, optiona, optionb, optionc, optiond, correctoption) VALUES
('Tenses', 'She _____ to school every day.', 'go', 'goes', 'going', 'gone', 2),
('Tenses', 'They _____ playing football when I saw them.', 'were', 'was', 'is', 'are', 1),
('Tenses', 'I _____ my homework already.', 'finish', 'finished', 'have finished', 'will finish', 3),
('Tenses', 'By next year, I _____ here for 10 years.', 'will work', 'will have worked', 'work', 'have worked', 2),
('Tenses', 'He _____ breakfast at 7 AM every morning.', 'have', 'has', 'having', 'had', 2),
('Tenses', 'We _____ to the cinema last night.', 'go', 'went', 'have gone', 'goes', 2),
('Tenses', 'She _____ in London since 2015.', 'lives', 'lived', 'has lived', 'is living', 3),
('Tenses', 'What _____ you doing at 8 PM yesterday?', 'are', 'were', 'was', 'is', 2),
('Tenses', 'The train _____ before we reached the station.', 'left', 'has left', 'had left', 'was leaving', 3),
('Tenses', 'I promise I _____ you tomorrow.', 'call', 'will call', 'am calling', 'called', 2),
('Tenses', 'She _____ French for three years now.', 'studies', 'has been studying', 'studied', 'is studying', 2),
('Tenses', 'When I got home, the children _____ asleep.', 'were', 'was', 'are', 'is', 1),
('Tenses', 'He usually _____ coffee, but today he _____ tea.', 'drink, drink', 'drinks, is drinking', 'is drinking, drinks', 'drank, drinks', 2),
('Tenses', 'I _____ the movie before, so I didn''t watch it again.', 'saw', 'have seen', 'had seen', 'was seeing', 3),
('Tenses', 'They _____ construction on the new mall next month.', 'start', 'will start', 'are starting', 'started', 3),
('Tenses', 'She _____ tired because she _____ for hours.', 'was, had been working', 'is, worked', 'was, was working', 'is, had worked', 1),
('Tenses', 'Where _____ you born?', 'are', 'were', 'was', 'is', 2),
('Tenses', 'I _____ to call you, but I forgot.', 'mean', 'meant', 'have meant', 'was meaning', 2),
('Tenses', 'This time next week, we _____ on the beach.', 'will relax', 'will be relaxing', 'relax', 'are relaxing', 2),
('Tenses', 'She never _____ to bed before 11 PM.', 'go', 'goes', 'going', 'went', 2),
('Tenses', 'I _____ my keys. I can''t find them anywhere.', 'lose', 'lost', 'have lost', 'am losing', 3),
('Tenses', 'While I _____ dinner, the phone _____.', 'cooked, rang', 'was cooking, rang', 'cooked, was ringing', 'was cooking, was ringing', 2),
('Tenses', 'The sun _____ in the east.', 'rise', 'rises', 'rose', 'is rising', 2),
('Tenses', 'They _____ married next Saturday.', 'get', 'will get', 'are getting', 'got', 3),
('Tenses', 'I _____ him twice this week already.', 'saw', 'have seen', 'see', 'am seeing', 2),
('Tenses', 'By the time you arrive, we _____ dinner.', 'finish', 'will finish', 'will have finished', 'finished', 3),
('Tenses', 'She _____ a new car last month.', 'buy', 'buys', 'bought', 'has bought', 3),
('Tenses', 'What _____ you do if you _____ a million dollars?', 'would, win', 'will, win', 'would, won', 'will, won', 3),
('Tenses', 'He _____ to the party if he _____ time.', 'will come, has', 'comes, has', 'would come, had', 'came, had', 1),
('Tenses', 'I _____ for you for over an hour!', 'wait', 'am waiting', 'have been waiting', 'waited', 3),
('Tenses', 'She _____ her arm when she _____ off her bike.', 'broke, fell', 'was breaking, fell', 'broke, was falling', 'was breaking, was falling', 1),
('Tenses', 'They _____ in this city for 20 years by 2025.', 'will live', 'will have lived', 'have lived', 'live', 2),
('Tenses', 'I _____ to the radio when the news _____.', 'listened, came', 'was listening, came', 'listened, was coming', 'was listening, was coming', 2),
('Tenses', 'He _____ his homework before dinner every day.', 'does', 'do', 'is doing', 'has done', 1),
('Tenses', 'We _____ to Paris twice so far.', 'go', 'went', 'have been', 'are going', 3),
('Tenses', 'Look at those clouds! It _____ rain.', 'will', 'is going to', 'shall', 'would', 2),
('Tenses', 'She _____ in a restaurant when I first met her.', 'worked', 'was working', 'has worked', 'works', 2),
('Tenses', 'I _____ you if you _____ me the truth.', 'help, tell', 'will help, tell', 'would help, told', 'helped, tell', 2),
('Tenses', 'He _____ his leg while he _____ football.', 'broke, was playing', 'broke, played', 'was breaking, played', 'was breaking, was playing', 1),
('Tenses', 'They _____ for us at the station when we arrive.', 'will wait', 'will be waiting', 'wait', 'are waiting', 2),
('Tenses', 'I _____ never _____ to Japan before.', 'have, been', 'has, been', 'had, been', 'did, go', 1),
('Tenses', 'She _____ her homework already when I called.', 'did', 'had done', 'has done', 'was doing', 2),
('Tenses', 'The phone _____ while I _____ a shower.', 'rang, was taking', 'was ringing, took', 'rang, took', 'was ringing, was taking', 1),
('Tenses', 'We _____ each other since elementary school.', 'know', 'knew', 'have known', 'are knowing', 3),
('Tenses', 'He _____ to become a doctor when he grows up.', 'wants', 'want', 'is wanting', 'wanted', 1),
('Tenses', 'I _____ TV when the lights went out.', 'watched', 'was watching', 'have watched', 'watch', 2),
('Tenses', 'They _____ the project by next Friday.', 'will complete', 'complete', 'will have completed', 'are completing', 3),
('Tenses', 'She _____ to the market every Sunday.', 'go', 'goes', 'went', 'is going', 2),
('Tenses', 'What _____ you _____ at this time yesterday?', 'were, doing', 'was, doing', 'did, do', 'are, doing', 1),
('Tenses', 'He _____ his car for five years now.', 'has', 'has had', 'had', 'is having', 2),
('Tenses', 'I _____ to bed early tonight because I _____ tired.', 'go, am', 'will go, am', 'am going, am', 'went, was', 2),
('Tenses', 'She _____ English for 10 years before she moved to England.', 'studied', 'had studied', 'has studied', 'was studying', 2),
('Tenses', 'They _____ a new house next year.', 'buy', 'will buy', 'are buying', 'bought', 2),
('Tenses', 'He never _____ late for work.', 'is', 'are', 'am', 'be', 1),
('Tenses', 'I _____ to the concert if I _____ tickets.', 'will go, get', 'go, get', 'would go, got', 'went, get', 1),
('Tenses', 'She _____ already _____ three cups of coffee today.', 'has, drunk', 'have, drunk', 'had, drunk', 'did, drink', 1),
('Tenses', 'When we arrived, the party _____.', 'started', 'had started', 'has started', 'was starting', 2),
('Tenses', 'He _____ his grandmother every weekend.', 'visit', 'visits', 'is visiting', 'visited', 2),
('Tenses', 'I _____ that movie three times already.', 'saw', 'have seen', 'see', 'am seeing', 2),
('Tenses', 'They _____ married for 25 years next June.', 'will be', 'will have been', 'have been', 'are', 2);

-- 2. ARTICLES (A, An, The) - 30 questions
INSERT INTO public.grammarquestions (GrammarType, questiontext, optiona, optionb, optionc, optiond, correctoption) VALUES
('Articles', 'She is _____ honest woman.', 'a', 'an', 'the', 'no article', 2),
('Articles', 'I need _____ umbrella. It''s raining.', 'a', 'an', 'the', 'no article', 2),
('Articles', '_____ sun rises in _____ east.', 'The, the', 'A, the', 'The, a', 'A, a', 1),
('Articles', 'He is _____ best student in the class.', 'a', 'an', 'the', 'no article', 3),
('Articles', 'I have _____ idea.', 'a', 'an', 'the', 'no article', 2),
('Articles', 'She works as _____ engineer.', 'a', 'an', 'the', 'no article', 2),
('Articles', 'They live in _____ United States.', 'a', 'an', 'the', 'no article', 3),
('Articles', 'Would you like _____ apple?', 'a', 'an', 'the', 'no article', 2),
('Articles', 'He is _____ European.', 'a', 'an', 'the', 'no article', 1),
('Articles', '_____ Mount Everest is highest mountain.', 'A', 'An', 'The', 'No article', 4),
('Articles', 'I saw _____ movie last night. _____ movie was excellent.', 'a, A', 'an, The', 'a, The', 'the, A', 3),
('Articles', 'She plays _____ piano beautifully.', 'a', 'an', 'the', 'no article', 3),
('Articles', 'He goes to _____ church every Sunday.', 'a', 'an', 'the', 'no article', 4),
('Articles', 'This is _____ useful tool.', 'a', 'an', 'the', 'no article', 1),
('Articles', 'She has _____ university degree.', 'a', 'an', 'the', 'no article', 1),
('Articles', '_____ Pacific Ocean is very deep.', 'A', 'An', 'The', 'No article', 3),
('Articles', 'I need _____ hour to finish this.', 'a', 'an', 'the', 'no article', 2),
('Articles', 'He is _____ only child in his family.', 'a', 'an', 'the', 'no article', 3),
('Articles', 'She went to _____ hospital to visit her friend.', 'a', 'an', 'the', 'no article', 3),
('Articles', 'What _____ beautiful day!', 'a', 'an', 'the', 'no article', 1),
('Articles', 'He works in _____ office downtown.', 'a', 'an', 'the', 'no article', 1),
('Articles', 'I had _____ egg for breakfast.', 'a', 'an', 'the', 'no article', 2),
('Articles', 'She is _____ richest woman in the world.', 'a', 'an', 'the', 'no article', 3),
('Articles', 'They went to _____ same school.', 'a', 'an', 'the', 'no article', 3),
('Articles', '_____ lions are dangerous animals.', 'A', 'An', 'The', 'No article', 4),
('Articles', 'He wants to be _____ actor.', 'a', 'an', 'the', 'no article', 2),
('Articles', 'I love _____ coffee in the morning.', 'a', 'an', 'the', 'no article', 4),
('Articles', 'This is _____ one-way street.', 'a', 'an', 'the', 'no article', 1),
('Articles', 'She is _____ best candidate for the job.', 'a', 'an', 'the', 'no article', 3),
('Articles', 'We stayed at _____ hotel by the beach.', 'a', 'an', 'the', 'no article', 1);

-- 3. PREPOSITIONS - 30 questions
INSERT INTO public.grammarquestions (GrammarType, questiontext, optiona, optionb, optionc, optiond, correctoption) VALUES
('Prepositions', 'She arrived _____ Paris yesterday.', 'to', 'in', 'at', 'on', 2),
('Prepositions', 'I usually wake up _____ 7 AM.', 'in', 'on', 'at', 'by', 3),
('Prepositions', 'We are going _____ vacation next week.', 'to', 'on', 'for', 'in', 2),
('Prepositions', 'He is interested _____ learning Spanish.', 'in', 'on', 'at', 'for', 1),
('Prepositions', 'She is afraid _____ spiders.', 'from', 'of', 'with', 'about', 2),
('Prepositions', 'I will meet you _____ the corner of the street.', 'in', 'on', 'at', 'by', 3),
('Prepositions', 'He has been waiting _____ two hours.', 'since', 'for', 'during', 'from', 2),
('Prepositions', 'She depends _____ her parents for money.', 'of', 'from', 'on', 'in', 3),
('Prepositions', 'I am good _____ mathematics.', 'in', 'on', 'at', 'with', 3),
('Prepositions', 'They got married _____ June.', 'in', 'on', 'at', 'by', 1),
('Prepositions', 'The book was written _____ Charles Dickens.', 'by', 'from', 'of', 'with', 1),
('Prepositions', 'I am looking forward _____ meeting you.', 'to', 'for', 'with', 'at', 1),
('Prepositions', 'She apologized _____ being late.', 'about', 'for', 'of', 'with', 2),
('Prepositions', 'He is responsible _____ this department.', 'for', 'of', 'with', 'about', 1),
('Prepositions', 'I prefer coffee _____ tea.', 'to', 'than', 'over', 'from', 1),
('Prepositions', 'She suffers _____ a serious illness.', 'from', 'of', 'with', 'by', 1),
('Prepositions', 'We walked _____ the park.', 'across', 'through', 'over', 'between', 2),
('Prepositions', 'He threw the ball _____ the window.', 'through', 'across', 'over', 'under', 1),
('Prepositions', 'She sat _____ me during the concert.', 'next', 'beside', 'besides', 'between', 2),
('Prepositions', 'I will finish this project _____ Friday.', 'in', 'on', 'at', 'by', 4),
('Prepositions', 'They are traveling _____ car.', 'by', 'with', 'in', 'on', 1),
('Prepositions', 'She is different _____ her sister.', 'than', 'from', 'to', 'with', 2),
('Prepositions', 'I agree _____ you completely.', 'to', 'with', 'on', 'for', 2),
('Prepositions', 'He insisted _____ paying the bill.', 'on', 'in', 'for', 'about', 1),
('Prepositions', 'She succeeded _____ passing the exam.', 'in', 'on', 'at', 'to', 1),
('Prepositions', 'I am tired _____ waiting.', 'from', 'of', 'with', 'about', 2),
('Prepositions', 'They divided the money _____ themselves.', 'among', 'between', 'with', 'in', 1),
('Prepositions', 'He is known _____ his generosity.', 'for', 'by', 'with', 'about', 1),
('Prepositions', 'She is married _____ a famous actor.', 'with', 'to', 'by', 'from', 2),
('Prepositions', 'I will be there _____ a moment.', 'in', 'on', 'at', 'by', 1);

-- 4. MODAL VERBS - 30 questions
INSERT INTO public.grammarquestions (GrammarType, questiontext, optiona, optionb, optionc, optiond, correctoption) VALUES
('Modal Verbs', 'You _____ smoke here. It''s prohibited.', 'mustn''t', 'don''t have to', 'may not', 'needn''t', 1),
('Modal Verbs', 'She _____ speak three languages fluently.', 'can', 'may', 'must', 'should', 1),
('Modal Verbs', 'You look tired. You _____ take a rest.', 'must', 'should', 'can', 'may', 2),
('Modal Verbs', '_____ I borrow your pen, please?', 'Must', 'Should', 'May', 'Need', 3),
('Modal Verbs', 'He _____ be at home. His car is in the driveway.', 'must', 'may', 'can', 'should', 1),
('Modal Verbs', 'You _____ worry. Everything will be fine.', 'mustn''t', 'don''t have to', 'shouldn''t', 'can''t', 3),
('Modal Verbs', 'I _____ go to the meeting, but I''m not sure.', 'must', 'might', 'should', 'can', 2),
('Modal Verbs', 'She _____ have forgotten about the appointment.', 'must', 'may', 'could', 'all of the above', 4),
('Modal Verbs', 'You _____ wear a uniform at this school.', 'have to', 'must', 'should', 'both a and b', 4),
('Modal Verbs', 'He _____ be very rich. He drives a Ferrari.', 'can', 'must', 'should', 'may', 2),
('Modal Verbs', 'I _____ help you if you want me to.', 'can', 'must', 'should', 'may', 1),
('Modal Verbs', 'You _____ pay for this. It''s free.', 'mustn''t', 'don''t have to', 'shouldn''t', 'can''t', 2),
('Modal Verbs', 'She _____ come to the party. She''s not feeling well.', 'might not', 'cannot', 'must not', 'should not', 1),
('Modal Verbs', 'We _____ leave early yesterday because of the snow.', 'had to', 'must', 'should', 'could', 1),
('Modal Verbs', 'You _____ eat so much junk food. It''s unhealthy.', 'mustn''t', 'shouldn''t', 'don''t have to', 'may not', 2),
('Modal Verbs', 'He _____ play the guitar when he was five.', 'can', 'could', 'may', 'might', 2),
('Modal Verbs', 'I _____ rather stay home tonight.', 'would', 'should', 'could', 'might', 1),
('Modal Verbs', 'She _____ be at work now. It''s only 6 AM.', 'can''t', 'mustn''t', 'shouldn''t', 'may not', 1),
('Modal Verbs', 'You _____ try the new restaurant downtown. It''s excellent.', 'must', 'should', 'can', 'might', 2),
('Modal Verbs', 'They _____ finish the project by Friday.', 'must', 'have to', 'need to', 'all of the above', 4),
('Modal Verbs', 'I _____ see clearly without my glasses.', 'can''t', 'mustn''t', 'shouldn''t', 'may not', 1),
('Modal Verbs', 'You _____ be kidding! That''s impossible.', 'must', 'can', 'may', 'should', 1),
('Modal Verbs', 'He _____ arrive late. Traffic is terrible today.', 'might', 'should', 'must', 'can', 1),
('Modal Verbs', 'We _____ hurry if we want to catch the train.', 'should', 'must', 'have to', 'all of the above', 4),
('Modal Verbs', 'She _____ speak to you now. She''s in a meeting.', 'can''t', 'may not', 'shouldn''t', 'both a and b', 4),
('Modal Verbs', 'I _____ have studied harder for the exam.', 'should', 'must', 'could', 'might', 1),
('Modal Verbs', 'You _____ ask for permission to leave early.', 'must', 'should', 'have to', 'all of the above', 4),
('Modal Verbs', 'He _____ be the one who took my book.', 'could', 'might', 'may', 'all of the above', 4),
('Modal Verbs', 'They _____ win the championship if they play well.', 'can', 'could', 'may', 'all of the above', 4),
('Modal Verbs', 'You _____ forget to lock the door.', 'mustn''t', 'don''t have to', 'shouldn''t', 'may not', 1);

-- 5. ACTIVE AND PASSIVE VOICE - 30 questions
INSERT INTO public.grammarquestions (GrammarType, questiontext, optiona, optionb, optionc, optiond, correctoption) VALUES
('Active Passive', 'The cake _____ by my mother.', 'was baked', 'baked', 'is bake', 'were baked', 1),
('Active Passive', 'They _____ a new house next year.', 'will build', 'will be built', 'build', 'are built', 1),
('Active Passive', 'The letter _____ yesterday.', 'sent', 'was sent', 'is sent', 'were sent', 2),
('Active Passive', 'A new school _____ in our town at the moment.', 'is being built', 'is building', 'builds', 'was built', 1),
('Active Passive', 'The movie _____ by millions of people.', 'watches', 'is watched', 'is watching', 'watch', 2),
('Active Passive', 'The homework _____ by the students already.', 'has done', 'has been done', 'have been done', 'did', 2),
('Active Passive', 'This book _____ in 1950.', 'wrote', 'was written', 'written', 'is written', 2),
('Active Passive', 'The window _____ by the boy.', 'break', 'was broken', 'broke', 'is break', 2),
('Active Passive', 'Coffee _____ in Brazil.', 'is grown', 'grows', 'grow', 'are grown', 1),
('Active Passive', 'The meeting _____ tomorrow.', 'will hold', 'will be held', 'holds', 'is holding', 2),
('Active Passive', 'My car _____ last week.', 'stole', 'was stolen', 'is stolen', 'were stolen', 2),
('Active Passive', 'The children _____ to the zoo every year.', 'take', 'are taken', 'took', 'were taken', 2),
('Active Passive', 'This room _____ every day.', 'cleans', 'is cleaned', 'clean', 'are cleaned', 2),
('Active Passive', 'The accident _____ by the police.', 'is investigating', 'is being investigated', 'investigates', 'investigated', 2),
('Active Passive', 'The project _____ before the deadline.', 'finished', 'was finished', 'is finished', 'has finished', 2),
('Active Passive', 'English _____ all over the world.', 'speaks', 'is spoken', 'speak', 'are spoken', 2),
('Active Passive', 'The thief _____ by the police yesterday.', 'caught', 'was caught', 'is caught', 'were caught', 2),
('Active Passive', 'The bridge _____ for two years now.', 'has built', 'has been built', 'is building', 'was built', 2),
('Active Passive', 'The invitation _____ by everyone.', 'received', 'was received', 'were received', 'is receive', 2),
('Active Passive', 'The problem _____ yet.', 'hasn''t solved', 'hasn''t been solved', 'didn''t solve', 'wasn''t solve', 2),
('Active Passive', 'These cookies _____ by my grandmother.', 'made', 'were made', 'are make', 'is made', 2),
('Active Passive', 'The new policy _____ by the manager.', 'will announce', 'will be announced', 'announces', 'is announcing', 2),
('Active Passive', 'The documents _____ carefully.', 'must handle', 'must be handled', 'must handling', 'must handled', 2),
('Active Passive', 'The awards _____ by the president.', 'presented', 'were presented', 'are present', 'present', 2),
('Active Passive', 'The house _____ since last year.', 'hasn''t painted', 'hasn''t been painted', 'didn''t paint', 'wasn''t painted', 2),
('Active Passive', 'All the tickets _____ for the concert.', 'sold out', 'were sold out', 'sell out', 'are sell out', 2),
('Active Passive', 'The patient _____ to the hospital immediately.', 'took', 'was taken', 'is take', 'were taken', 2),
('Active Passive', 'The results _____ next week.', 'will publish', 'will be published', 'publish', 'are publish', 2),
('Active Passive', 'This song _____ by many artists.', 'has recorded', 'has been recorded', 'recorded', 'was record', 2),
('Active Passive', 'The building _____ in the earthquake.', 'destroyed', 'was destroyed', 'is destroyed', 'were destroyed', 2);

-- 6. CONDITIONALS - 30 questions
INSERT INTO public.grammarquestions (GrammarType, questiontext, optiona, optionb, optionc, optiond, correctoption) VALUES
('Conditionals', 'If it rains, we _____ the picnic.', 'cancel', 'will cancel', 'would cancel', 'cancelled', 2),
('Conditionals', 'If I _____ you, I would accept the job.', 'am', 'were', 'was', 'be', 2),
('Conditionals', 'If she had studied, she _____ the exam.', 'would pass', 'would have passed', 'will pass', 'passes', 2),
('Conditionals', 'If you heat ice, it _____ .', 'melts', 'will melt', 'would melt', 'melt', 1),
('Conditionals', 'If he _____ earlier, he wouldn''t have missed the train.', 'left', 'had left', 'leaves', 'would leave', 2),
('Conditionals', 'What _____ you do if you won the lottery?', 'will', 'would', 'do', 'did', 2),
('Conditionals', 'If I _____ time, I will help you.', 'have', 'had', 'would have', 'will have', 1),
('Conditionals', 'If they had invited us, we _____ .', 'would come', 'would have come', 'will come', 'came', 2),
('Conditionals', 'If you _____ red and blue, you get purple.', 'mix', 'will mix', 'mixed', 'would mix', 1),
('Conditionals', 'She would be happy if she _____ a new job.', 'gets', 'got', 'will get', 'would get', 2),
('Conditionals', 'If I _____ that, I would have been angry.', 'were you', 'had been you', 'am you', 'was you', 1),
('Conditionals', 'If you don''t hurry, you _____ the bus.', 'miss', 'will miss', 'would miss', 'missed', 2),
('Conditionals', 'If I _____ his number, I would call him.', 'know', 'knew', 'have known', 'known', 2),
('Conditionals', 'If we _____ earlier, we wouldn''t be stuck in traffic.', 'left', 'had left', 'leave', 'would leave', 2),
('Conditionals', 'If she _____ the job, she will move to London.', 'gets', 'got', 'would get', 'had got', 1),
('Conditionals', 'I would have helped you if I _____ there.', 'were', 'had been', 'am', 'was', 2),
('Conditionals', 'If you freeze water, it _____ into ice.', 'turns', 'will turn', 'would turn', 'turned', 1),
('Conditionals', 'If he were more careful, he _____ fewer mistakes.', 'makes', 'would make', 'will make', 'made', 2),
('Conditionals', 'If I _____ you were coming, I would have waited.', 'know', 'had known', 'knew', 'have known', 2),
('Conditionals', 'She would travel more if she _____ more money.', 'has', 'had', 'will have', 'would have', 2),
('Conditionals', 'If you _____ your keys, you can''t get in.', 'lose', 'lost', 'will lose', 'would lose', 1),
('Conditionals', 'If they _____ the lottery, they would buy a house.', 'win', 'won', 'will win', 'would win', 2),
('Conditionals', 'If I _____ the answer, I would tell you.', 'know', 'knew', 'have known', 'known', 2),
('Conditionals', 'If she _____ harder, she would have passed the test.', 'studied', 'had studied', 'studies', 'would study', 2),
('Conditionals', 'If you mix yellow and blue, you _____ green.', 'get', 'will get', 'would get', 'got', 1),
('Conditionals', 'He would have called if he _____ your number.', 'had', 'had had', 'has', 'would have', 2),
('Conditionals', 'If I _____ the manager, I would change the policy.', 'am', 'were', 'was', 'be', 2),
('Conditionals', 'If it _____ tomorrow, we will stay home.', 'snows', 'snowed', 'would snow', 'had snowed', 1),
('Conditionals', 'I would buy a car if I _____ enough money.', 'have', 'had', 'will have', 'would have', 2),
('Conditionals', 'If they had known, they _____ different.', 'would do', 'would have done', 'will do', 'do', 2);

-- 7. REPORTED SPEECH - 30 questions
INSERT INTO public.grammarquestions (GrammarType, questiontext, optiona, optionb, optionc, optiond, correctoption) VALUES
('Reported Speech', 'She said, "I am tired." → She said that she _____ tired.', 'is', 'was', 'am', 'were', 2),
('Reported Speech', 'He said, "I will call you." → He said that he _____ call me.', 'will', 'would', 'can', 'may', 2),
('Reported Speech', 'They said, "We have finished." → They said that they _____ finished.', 'have', 'had', 'has', 'will have', 2),
('Reported Speech', 'She asked, "Do you like coffee?" → She asked if I _____ coffee.', 'like', 'liked', 'likes', 'am liking', 2),
('Reported Speech', 'He said, "I am working now." → He said that he _____ then.', 'is working', 'was working', 'has been working', 'works', 2),
('Reported Speech', 'She said, "I will help you." → She promised that she _____ help me.', 'will', 'would', 'can', 'may', 2),
('Reported Speech', 'He said, "I can swim." → He said that he _____ swim.', 'can', 'could', 'may', 'might', 2),
('Reported Speech', 'They said, "We were sleeping." → They said that they _____ sleeping.', 'were', 'had been', 'have been', 'are', 2),
('Reported Speech', 'She said, "I must go." → She said that she _____ go.', 'must', 'had to', 'has to', 'have to', 2),
('Reported Speech', 'He asked, "Where do you live?" → He asked where I _____.', 'live', 'lived', 'am living', 'was living', 2),
('Reported Speech', 'She said, "I will be there." → She said that she _____ there.', 'will be', 'would be', 'is', 'was', 2),
('Reported Speech', 'He said, "I have seen this movie." → He said that he _____ that movie.', 'has seen', 'had seen', 'saw', 'have seen', 2),
('Reported Speech', 'They said, "We are leaving." → They said that they _____ .', 'are leaving', 'were leaving', 'have left', 'left', 2),
('Reported Speech', 'She asked, "Did you see the accident?" → She asked if I _____ the accident.', 'saw', 'had seen', 'have seen', 'see', 2),
('Reported Speech', 'He said, "I may be late." → He said that he _____ be late.', 'may', 'might', 'can', 'will', 2),
('Reported Speech', 'She said, "I don''t like it." → She said that she _____ like it.', 'doesn''t', 'didn''t', 'don''t', 'hadn''t', 2),
('Reported Speech', 'He asked, "What time is it?" → He asked what time it _____.', 'is', 'was', 'were', 'has been', 2),
('Reported Speech', 'She said, "I was waiting." → She said that she _____ .', 'was waiting', 'had been waiting', 'has been waiting', 'is waiting', 2),
('Reported Speech', 'He said, "I will have finished by then." → He said that he _____ by then.', 'will have finished', 'would have finished', 'had finished', 'finished', 2),
('Reported Speech', 'She asked, "Can you help me?" → She asked if I _____ help her.', 'can', 'could', 'may', 'should', 2),
('Reported Speech', 'They said, "We have been waiting." → They said that they _____ .', 'have been waiting', 'had been waiting', 'were waiting', 'are waiting', 2),
('Reported Speech', 'He said, "I shall call you." → He said that he _____ call me.', 'shall', 'would', 'should', 'will', 2),
('Reported Speech', 'She said, "I love you." → She told me that she _____ me.', 'loves', 'loved', 'love', 'is loving', 2),
('Reported Speech', 'He asked, "Why are you crying?" → He asked why I _____ crying.', 'am', 'was', 'were', 'have been', 2),
('Reported Speech', 'She said, "I will be working." → She said that she _____ .', 'will be working', 'would be working', 'was working', 'worked', 2),
('Reported Speech', 'He said, "I could help." → He said that he _____ help.', 'could', 'can', 'may', 'might', 1),
('Reported Speech', 'They asked, "Are you ready?" → They asked if I _____ ready.', 'am', 'was', 'were', 'have been', 2),
('Reported Speech', 'She said, "I had finished." → She said that she _____ finished.', 'had', 'has', 'have', 'would have', 1),
('Reported Speech', 'He said, "I must leave now." → He said that he _____ leave then.', 'must', 'had to', 'has to', 'have to', 2),
('Reported Speech', 'She asked, "What are you doing?" → She asked what I _____ doing.', 'am', 'was', 'were', 'have been', 2);

-- 8. SUBJECT-VERB AGREEMENT - 30 questions
INSERT INTO public.grammarquestions (GrammarType, questiontext, optiona, optionb, optionc, optiond, correctoption) VALUES
('Subject-Verb Agreement', 'The dog _____ barking loudly.', 'are', 'is', 'am', 'were', 2),
('Subject-Verb Agreement', 'The children _____ playing in the park.', 'is', 'am', 'are', 'was', 3),
('Subject-Verb Agreement', 'Neither of the answers _____ correct.', 'are', 'is', 'am', 'were', 2),
('Subject-Verb Agreement', 'Each of the students _____ a book.', 'have', 'has', 'are having', 'were having', 2),
('Subject-Verb Agreement', 'The news _____ very interesting.', 'are', 'is', 'am', 'were', 2),
('Subject-Verb Agreement', 'Mathematics _____ my favorite subject.', 'are', 'is', 'am', 'were', 2),
('Subject-Verb Agreement', 'Either John or his brothers _____ coming.', 'is', 'am', 'are', 'be', 3),
('Subject-Verb Agreement', 'The committee _____ made its decision.', 'has', 'have', 'are', 'were', 1),
('Subject-Verb Agreement', 'There _____ many people at the concert.', 'is', 'am', 'are', 'was', 3),
('Subject-Verb Agreement', 'The number of students _____ increasing.', 'are', 'is', 'am', 'were', 2),
('Subject-Verb Agreement', 'A number of students _____ absent.', 'is', 'am', 'are', 'was', 3),
('Subject-Verb Agreement', 'The police _____ investigating the crime.', 'is', 'am', 'are', 'was', 3),
('Subject-Verb Agreement', 'My family _____ very supportive.', 'is', 'am', 'are', 'were', 1),
('Subject-Verb Agreement', 'Ten dollars _____ not enough for lunch.', 'are', 'is', 'am', 'were', 2),
('Subject-Verb Agreement', 'The scissors _____ sharp.', 'is', 'am', 'are', 'was', 3),
('Subject-Verb Agreement', 'Neither the teacher nor the students _____ happy.', 'is', 'am', 'are', 'was', 3),
('Subject-Verb Agreement', 'The United Nations _____ its headquarters in New York.', 'have', 'has', 'are having', 'were having', 2),
('Subject-Verb Agreement', 'Everyone _____ to succeed.', 'want', 'wants', 'are wanting', 'were wanting', 2),
('Subject-Verb Agreement', 'The pair of shoes _____ expensive.', 'are', 'is', 'am', 'were', 2),
('Subject-Verb Agreement', 'Bread and butter _____ my favorite breakfast.', 'are', 'is', 'am', 'were', 2),
('Subject-Verb Agreement', 'The athlete, along with his coach, _____ arrived.', 'have', 'has', 'are', 'were', 2),
('Subject-Verb Agreement', 'Either the manager or the employees _____ responsible.', 'is', 'am', 'are', 'be', 3),
('Subject-Verb Agreement', 'The furniture _____ new.', 'are', 'is', 'am', 'were', 2),
('Subject-Verb Agreement', 'One of my friends _____ moving to London.', 'are', 'is', 'am', 'were', 2),
('Subject-Verb Agreement', 'The team _____ playing well today.', 'are', 'is', 'am', 'were', 2),
('Subject-Verb Agreement', 'Physics _____ not an easy subject.', 'are', 'is', 'am', 'were', 2),
('Subject-Verb Agreement', 'Each of the candidates _____ qualified.', 'are', 'is', 'am', 'were', 2),
('Subject-Verb Agreement', 'The jury _____ divided in their opinions.', 'is', 'are', 'am', 'was', 2),
('Subject-Verb Agreement', 'Here _____ the books you wanted.', 'is', 'am', 'are', 'be', 3),
('Subject-Verb Agreement', 'More than one student _____ late.', 'were', 'was', 'are', 'is', 2);

-- 9. GERUNDS AND INFINITIVES - 30 questions
INSERT INTO public.grammarquestions (GrammarType, questiontext, optiona, optionb, optionc, optiond, correctoption) VALUES
('Gerunds Infinitives', 'I enjoy _____ to music.', 'listen', 'to listen', 'listening', 'listened', 3),
('Gerunds Infinitives', 'She wants _____ a doctor.', 'become', 'to become', 'becoming', 'became', 2),
('Gerunds Infinitives', 'He stopped _____ coffee last year.', 'drink', 'to drink', 'drinking', 'drank', 3),
('Gerunds Infinitives', 'It''s important _____ early.', 'arrive', 'to arrive', 'arriving', 'arrived', 2),
('Gerunds Infinitives', 'I look forward to _____ you.', 'see', 'to see', 'seeing', 'saw', 3),
('Gerunds Infinitives', 'She avoided _____ to him.', 'talk', 'to talk', 'talking', 'talked', 3),
('Gerunds Infinitives', 'They decided _____ the house.', 'sell', 'to sell', 'selling', 'sold', 2),
('Gerunds Infinitives', 'I can''t help _____ about it.', 'worry', 'to worry', 'worrying', 'worried', 3),
('Gerunds Infinitives', 'He suggested _____ to the beach.', 'go', 'to go', 'going', 'went', 3),
('Gerunds Infinitives', 'She agreed _____ me with my homework.', 'help', 'to help', 'helping', 'helped', 2),
('Gerunds Infinitives', 'I remember _____ the door.', 'lock', 'to lock', 'locking', 'locked', 3),
('Gerunds Infinitives', 'He forgot _____ the milk.', 'buy', 'to buy', 'buying', 'bought', 2),
('Gerunds Infinitives', 'She is good at _____ languages.', 'learn', 'to learn', 'learning', 'learned', 3),
('Gerunds Infinitives', 'They are interested in _____ abroad.', 'work', 'to work', 'working', 'worked', 3),
('Gerunds Infinitives', 'I would like _____ you my friend.', 'introduce', 'to introduce', 'introducing', 'introduced', 2),
('Gerunds Infinitives', 'He kept _____ the same question.', 'ask', 'to ask', 'asking', 'asked', 3),
('Gerunds Infinitives', 'She promised _____ me back soon.', 'call', 'to call', 'calling', 'called', 2),
('Gerunds Infinitives', 'I don''t mind _____ late.', 'work', 'to work', 'working', 'worked', 3),
('Gerunds Infinitives', 'They considered _____ a new car.', 'buy', 'to buy', 'buying', 'bought', 3),
('Gerunds Infinitives', 'He learned _____ at a young age.', 'swim', 'to swim', 'swimming', 'swam', 2),
('Gerunds Infinitives', 'I spent hours _____ for the test.', 'study', 'to study', 'studying', 'studied', 3),
('Gerunds Infinitives', 'She refused _____ the truth.', 'tell', 'to tell', 'telling', 'told', 2),
('Gerunds Infinitives', 'He is used to _____ up early.', 'wake', 'to wake', 'waking', 'woke', 3),
('Gerunds Infinitives', 'I can''t afford _____ a new phone.', 'buy', 'to buy', 'buying', 'bought', 2),
('Gerunds Infinitives', 'She denied _____ the money.', 'steal', 'to steal', 'stealing', 'stole', 3),
('Gerunds Infinitives', 'They expected _____ by 6 PM.', 'arrive', 'to arrive', 'arriving', 'arrived', 2),
('Gerunds Infinitives', 'I appreciate you _____ me.', 'help', 'to help', 'helping', 'helped', 3),
('Gerunds Infinitives', 'He finished _____ the report.', 'write', 'to write', 'writing', 'wrote', 3),
('Gerunds Infinitives', 'She pretended _____ asleep.', 'be', 'to be', 'being', 'was', 2),
('Gerunds Infinitives', 'They risked _____ everything.', 'lose', 'to lose', 'losing', 'lost', 3);

-- 10. ADJECTIVES AND ADVERBS - 30 questions
INSERT INTO public.grammarquestions (GrammarType, questiontext, optiona, optionb, optionc, optiond, correctoption) VALUES
('Adjectives Adverbs', 'She sings _____ .', 'beautiful', 'beautifully', 'beauty', 'beautify', 2),
('Adjectives Adverbs', 'He is a _____ driver.', 'careful', 'carefully', 'care', 'caring', 1),
('Adjectives Adverbs', 'This is a _____ day.', 'lovely', 'lovelily', 'love', 'loving', 1),
('Adjectives Adverbs', 'She speaks English _____ .', 'good', 'well', 'nice', 'great', 2),
('Adjectives Adverbs', 'He ran _____ to catch the bus.', 'quick', 'quickly', 'quicken', 'quickness', 2),
('Adjectives Adverbs', 'The food smells _____ .', 'delicious', 'deliciously', 'delight', 'delightful', 1),
('Adjectives Adverbs', 'She is _____ intelligent.', 'extreme', 'extremely', 'extent', 'extensive', 2),
('Adjectives Adverbs', 'He works _____ than his brother.', 'hard', 'harder', 'hardest', 'hardly', 2),
('Adjectives Adverbs', 'This is the _____ movie I''ve ever seen.', 'good', 'better', 'best', 'well', 3),
('Adjectives Adverbs', 'She arrived _____ than expected.', 'late', 'later', 'latest', 'latter', 2),
('Adjectives Adverbs', 'He is a _____ worker.', 'slow', 'slowly', 'slowness', 'slowly', 1),
('Adjectives Adverbs', 'She looked _____ at the news.', 'sad', 'sadly', 'sadness', 'sadden', 2),
('Adjectives Adverbs', 'The soup tastes _____ .', 'good', 'well', 'nicely', 'greatly', 1),
('Adjectives Adverbs', 'He drives _____ in bad weather.', 'careful', 'carefully', 'care', 'caring', 2),
('Adjectives Adverbs', 'She is _____ than her sister.', 'tall', 'taller', 'tallest', 'more tall', 2),
('Adjectives Adverbs', 'This is a _____ difficult problem.', 'surprise', 'surprisingly', 'surprised', 'surprising', 2),
('Adjectives Adverbs', 'He felt _____ after the exam.', 'happy', 'happily', 'happiness', 'happier', 1),
('Adjectives Adverbs', 'She speaks _____ than I do.', 'fluent', 'more fluently', 'fluently', 'most fluent', 2),
('Adjectives Adverbs', 'The weather is _____ today.', 'beautiful', 'beautifully', 'beauty', 'beautify', 1),
('Adjectives Adverbs', 'He arrived _____ .', 'punctual', 'punctually', 'punctuality', 'punctualize', 2),
('Adjectives Adverbs', 'She is _____ tired to go out.', 'too', 'very', 'so', 'much', 1),
('Adjectives Adverbs', 'He speaks English _____ .', 'perfect', 'perfectly', 'perfection', 'perfective', 2),
('Adjectives Adverbs', 'This is a _____ quiet place.', 'relative', 'relatively', 'relation', 'relate', 2),
('Adjectives Adverbs', 'She sings _____ of all.', 'beautiful', 'more beautiful', 'most beautifully', 'beautifully', 3),
('Adjectives Adverbs', 'He is _____ interested in sports.', 'deep', 'deeply', 'depth', 'deepen', 2),
('Adjectives Adverbs', 'The coffee is _____ hot to drink.', 'too', 'very', 'so', 'much', 1),
('Adjectives Adverbs', 'She wrote _____ than I did.', 'careful', 'more carefully', 'carefully', 'most careful', 2),
('Adjectives Adverbs', 'He is a _____ honest man.', 'very', 'much', 'too', 'so', 1),
('Adjectives Adverbs', 'The music sounds _____ .', 'loud', 'loudly', 'loudness', 'louder', 1),
('Adjectives Adverbs', 'She completed the test _____ .', 'easy', 'easily', 'ease', 'easier', 2);

-- 11. PRONOUNS - 30 questions
INSERT INTO public.grammarquestions (GrammarType, questiontext, optiona, optionb, optionc, optiond, correctoption) VALUES
('Pronouns', '_____ am going to the store.', 'I', 'Me', 'My', 'Mine', 1),
('Pronouns', 'This is _____ book.', 'I', 'me', 'my', 'mine', 3),
('Pronouns', 'That car is _____ .', 'her', 'she', 'hers', 'him', 3),
('Pronouns', '_____ are going to the party.', 'Him and I', 'He and I', 'Him and me', 'He and me', 2),
('Pronouns', 'She gave the gift to _____ .', 'I', 'me', 'my', 'mine', 2),
('Pronouns', 'The cat washed _____ .', 'itself', 'itself', 'its', 'it', 1),
('Pronouns', 'We did it _____ .', 'our', 'ours', 'ourselves', 'us', 3),
('Pronouns', 'Is this pen _____ ?', 'your', 'yours', 'you', 'yourselves', 2),
('Pronouns', '_____ of them is correct.', 'Both', 'Either', 'All', 'None', 2),
('Pronouns', 'I want _____ to know the truth.', 'they', 'them', 'their', 'theirs', 2),
('Pronouns', 'She is taller than _____ .', 'I', 'me', 'my', 'mine', 1),
('Pronouns', 'The book is _____ .', 'my', 'mine', 'me', 'I', 2),
('Pronouns', '_____ are my friends.', 'These', 'This', 'That', 'It', 1),
('Pronouns', 'He hurt _____ while playing.', 'him', 'himself', 'his', 'he', 2),
('Pronouns', '_____ was a great movie.', 'It', 'Its', 'It''s', 'Itself', 1),
('Pronouns', 'She bought _____ a new dress.', 'her', 'herself', 'hers', 'she', 2),
('Pronouns', 'I like _____ of them equally.', 'each', 'every', 'all', 'some', 3),
('Pronouns', '_____ is the man who helped me.', 'This', 'These', 'Those', 'They', 1),
('Pronouns', 'He and _____ are cousins.', 'I', 'me', 'my', 'mine', 1),
('Pronouns', 'The students did _____ homework.', 'their', 'theirs', 'them', 'themselves', 1),
('Pronouns', '_____ of the answers are correct.', 'Neither', 'None', 'Both', 'Either', 3),
('Pronouns', 'She is the one _____ won the prize.', 'who', 'whom', 'which', 'whose', 1),
('Pronouns', 'The man to _____ I spoke was friendly.', 'who', 'whom', 'which', 'whose', 2),
('Pronouns', '_____ car is this?', 'Who', 'Whom', 'Whose', 'Which', 3),
('Pronouns', 'I hurt _____ .', 'me', 'myself', 'my', 'mine', 2),
('Pronouns', 'They enjoyed _____ at the party.', 'their', 'themselves', 'them', 'theirs', 2),
('Pronouns', 'This is _____ house, not yours.', 'our', 'ours', 'us', 'we', 1),
('Pronouns', '_____ are you waiting for?', 'Who', 'Whom', 'Which', 'What', 2),
('Pronouns', 'The winner is _____ .', 'her', 'she', 'hers', 'herself', 2),
('Pronouns', 'Everyone must bring _____ own lunch.', 'their', 'his', 'her', 'its', 1);

-- 12. CONJUNCTIONS - 30 questions
INSERT INTO public.grammarquestions (GrammarType, questiontext, optiona, optionb, optionc, optiond, correctoption) VALUES
('Conjunctions', 'I like coffee _____ tea.', 'and', 'but', 'or', 'so', 1),
('Conjunctions', 'She is smart _____ lazy.', 'and', 'but', 'or', 'so', 2),
('Conjunctions', 'Would you like tea _____ coffee?', 'and', 'but', 'or', 'so', 3),
('Conjunctions', 'He studied hard, _____ he passed the exam.', 'and', 'but', 'or', 'so', 4),
('Conjunctions', 'I was tired, _____ I went to bed early.', 'and', 'but', 'or', 'so', 4),
('Conjunctions', 'She didn''t come to the party _____ she was sick.', 'because', 'so', 'but', 'and', 1),
('Conjunctions', 'I will go _____ you go.', 'if', 'unless', 'until', 'although', 1),
('Conjunctions', 'He is rich, _____ he is not happy.', 'and', 'but', 'or', 'so', 2),
('Conjunctions', 'Wait here _____ I come back.', 'until', 'if', 'unless', 'because', 1),
('Conjunctions', 'I can''t go out _____ I finish my homework.', 'if', 'unless', 'until', 'because', 3),
('Conjunctions', '_____ it was raining, we went out.', 'Although', 'Because', 'Since', 'If', 1),
('Conjunctions', 'She speaks English _____ French.', 'and', 'but', 'or', 'so', 1),
('Conjunctions', 'He is both intelligent _____ hardworking.', 'and', 'but', 'or', 'nor', 1),
('Conjunctions', 'I was tired, _____ I continued working.', 'and', 'but', 'or', 'so', 2),
('Conjunctions', 'She is either at home _____ at work.', 'and', 'but', 'or', 'nor', 3),
('Conjunctions', 'He didn''t study, _____ he failed the test.', 'so', 'but', 'and', 'or', 1),
('Conjunctions', 'I will call you _____ I arrive.', 'when', 'if', 'unless', 'until', 1),
('Conjunctions', 'She is both beautiful _____ intelligent.', 'and', 'but', 'or', 'nor', 1),
('Conjunctions', 'He is poor, _____ he is honest.', 'and', 'but', 'or', 'so', 2),
('Conjunctions', 'You will pass _____ you study hard.', 'if', 'unless', 'until', 'although', 1),
('Conjunctions', 'I like him _____ he is kind.', 'because', 'so', 'but', 'and', 1),
('Conjunctions', 'She didn''t call, _____ she promised to.', 'although', 'because', 'so', 'and', 1),
('Conjunctions', 'He is neither tall _____ short.', 'and', 'but', 'or', 'nor', 4),
('Conjunctions', 'I woke up late, _____ I missed the bus.', 'so', 'but', 'and', 'or', 1),
('Conjunctions', '_____ she was tired, she helped me.', 'Although', 'Because', 'Since', 'If', 1),
('Conjunctions', 'She worked hard _____ she could succeed.', 'so that', 'because', 'although', 'if', 1),
('Conjunctions', 'We stayed inside _____ the rain.', 'because of', 'because', 'so', 'but', 1),
('Conjunctions', 'He is smart, _____ he doesn''t study.', 'but', 'and', 'or', 'so', 1),
('Conjunctions', 'I will go to the party _____ I am invited.', 'if', 'unless', 'until', 'although', 1),
('Conjunctions', 'She was happy _____ she received the gift.', 'when', 'if', 'unless', 'until', 1);

-- 13. COMPARATIVES AND SUPERLATIVES - 30 questions
INSERT INTO public.grammarquestions (GrammarType, questiontext, optiona, optionb, optionc, optiond, correctoption) VALUES
('Comparatives Superlatives', 'This is _____ than that.', 'good', 'better', 'best', 'well', 2),
('Comparatives Superlatives', 'She is _____ student in the class.', 'smart', 'smarter', 'smartest', 'most smart', 3),
('Comparatives Superlatives', 'He runs _____ than his brother.', 'fast', 'faster', 'fastest', 'more fast', 2),
('Comparatives Superlatives', 'This is _____ day of my life.', 'happy', 'happier', 'happiest', 'most happy', 3),
('Comparatives Superlatives', 'She is _____ beautiful than her sister.', 'more', 'most', 'much', 'very', 1),
('Comparatives Superlatives', 'This is the _____ movie I''ve ever seen.', 'good', 'better', 'best', 'well', 3),
('Comparatives Superlatives', 'He is _____ than his father.', 'tall', 'taller', 'tallest', 'more tall', 2),
('Comparatives Superlatives', 'She speaks _____ of all.', 'clearly', 'more clearly', 'most clearly', 'clearer', 3),
('Comparatives Superlatives', 'This problem is _____ than the last one.', 'difficult', 'more difficult', 'most difficult', 'difficultest', 2),
('Comparatives Superlatives', 'He is the _____ person I know.', 'kind', 'kinder', 'kindest', 'more kind', 3),
('Comparatives Superlatives', 'She is _____ than me.', 'old', 'older', 'oldest', 'more old', 2),
('Comparatives Superlatives', 'This is _____ expensive restaurant in the city.', 'more', 'most', 'the most', 'much', 3),
('Comparatives Superlatives', 'He works _____ than anyone else.', 'hard', 'harder', 'hardest', 'more hard', 2),
('Comparatives Superlatives', 'She is _____ intelligent than her brother.', 'more', 'most', 'much', 'very', 1),
('Comparatives Superlatives', 'This is _____ book I''ve ever read.', 'interesting', 'more interesting', 'most interesting', 'the most interesting', 4),
('Comparatives Superlatives', 'He is _____ than his brother.', 'strong', 'stronger', 'strongest', 'more strong', 2),
('Comparatives Superlatives', 'She is _____ person I know.', 'funny', 'funnier', 'funniest', 'most funny', 3),
('Comparatives Superlatives', 'This car is _____ than that one.', 'fast', 'faster', 'fastest', 'more fast', 2),
('Comparatives Superlatives', 'He is _____ player on the team.', 'good', 'better', 'best', 'well', 3),
('Comparatives Superlatives', 'She is _____ than her mother.', 'beautiful', 'more beautiful', 'most beautiful', 'beautifuler', 2),
('Comparatives Superlatives', 'This is _____ difficult question of all.', 'more', 'most', 'the most', 'much', 3),
('Comparatives Superlatives', 'He runs _____ than me.', 'quickly', 'more quickly', 'most quickly', 'quicklier', 2),
('Comparatives Superlatives', 'She is _____ than her sister.', 'nice', 'nicer', 'nicest', 'more nice', 2),
('Comparatives Superlatives', 'This is _____ situation possible.', 'bad', 'worse', 'worst', 'baddest', 3),
('Comparatives Superlatives', 'He is _____ now than before.', 'happy', 'happier', 'happiest', 'more happy', 2),
('Comparatives Superlatives', 'She is _____ singer in the competition.', 'good', 'better', 'best', 'well', 3),
('Comparatives Superlatives', 'This is _____ than nothing.', 'good', 'better', 'best', 'well', 2),
('Comparatives Superlatives', 'He is _____ of the two brothers.', 'tall', 'taller', 'tallest', 'the taller', 4),
('Comparatives Superlatives', 'She speaks English _____ than me.', 'fluent', 'more fluently', 'most fluently', 'fluently', 2),
('Comparatives Superlatives', 'This is _____ beautiful city I''ve visited.', 'more', 'most', 'the most', 'much', 3);

-- 14. QUESTIONS AND QUESTION TAGS - 30 questions
INSERT INTO public.grammarquestions (GrammarType, questiontext, optiona, optionb, optionc, optiond, correctoption) VALUES
('Questions Tags', 'You are coming to the party, _____?', 'aren''t you', 'are you', 'don''t you', 'do you', 1),
('Questions Tags', 'She speaks English, _____?', 'does she', 'doesn''t she', 'is she', 'isn''t she', 2),
('Questions Tags', 'He didn''t go to school, _____?', 'did he', 'didn''t he', 'does he', 'doesn''t he', 1),
('Questions Tags', 'They have finished, _____?', 'have they', 'haven''t they', 'do they', 'don''t they', 2),
('Questions Tags', 'You can swim, _____?', 'can you', 'can''t you', 'do you', 'don''t you', 2),
('Questions Tags', 'Let''s go for a walk, _____?', 'shall we', 'will we', 'can we', 'do we', 1),
('Questions Tags', 'Open the door, _____?', 'will you', 'won''t you', 'can you', 'do you', 1),
('Questions Tags', 'I am late, _____?', 'am I', 'aren''t I', 'amn''t I', 'are I', 2),
('Questions Tags', 'She was sleeping, _____?', 'was she', 'wasn''t she', 'did she', 'didn''t she', 2),
('Questions Tags', 'They will arrive soon, _____?', 'will they', 'won''t they', 'do they', 'don''t they', 2),
('Questions Tags', 'He has a car, _____?', 'has he', 'hasn''t he', 'does he', 'doesn''t he', 4),
('Questions Tags', 'You like pizza, _____?', 'like you', 'don''t you', 'do you', 'did you', 2),
('Questions Tags', 'She went to Paris, _____?', 'did she', 'didn''t she', 'does she', 'doesn''t she', 2),
('Questions Tags', 'We should leave now, _____?', 'should we', 'shouldn''t we', 'shall we', 'will we', 2),
('Questions Tags', 'Nothing happened, _____?', 'did it', 'didn''t it', 'does it', 'doesn''t it', 1),
('Questions Tags', 'Everyone is here, _____?', 'is everyone', 'aren''t they', 'isn''t everyone', 'are they', 2),
('Questions Tags', 'Let me help you, _____?', 'will you', 'shall I', 'can I', 'may I', 2),
('Questions Tags', 'She''d better come, _____?', 'had she', 'hadn''t she', 'would she', 'wouldn''t she', 2),
('Questions Tags', 'He used to smoke, _____?', 'used he', 'didn''t he', 'usedn''t he', 'doesn''t he', 2),
('Questions Tags', 'I''m supposed to go, _____?', 'am I', 'aren''t I', 'am I not', 'is I', 2),
('Questions Tags', 'She seldom visits, _____?', 'does she', 'doesn''t she', 'is she', 'isn''t she', 1),
('Questions Tags', 'Nobody called, _____?', 'did they', 'didn''t they', 'did he', 'didn''t he', 1),
('Questions Tags', 'You''d like some coffee, _____?', 'would you', 'wouldn''t you', 'had you', 'hadn''t you', 2),
('Questions Tags', 'They rarely travel, _____?', 'do they', 'don''t they', 'are they', 'aren''t they', 1),
('Questions Tags', 'Don''t forget to call, _____?', 'will you', 'won''t you', 'do you', 'don''t you', 1),
('Questions Tags', 'She must be tired, _____?', 'must she', 'mustn''t she', 'is she', 'isn''t she', 2),
('Questions Tags', 'He had left, _____?', 'had he', 'hadn''t he', 'did he', 'didn''t he', 2),
('Questions Tags', 'You''re coming with us, _____?', 'are you', 'aren''t you', 'do you', 'don''t you', 2),
('Questions Tags', 'It''s a beautiful day, _____?', 'is it', 'isn''t it', 'does it', 'doesn''t it', 2),
('Questions Tags', 'She won''t mind, _____?', 'will she', 'won''t she', 'does she', 'doesn''t she', 1);

-- 15. PHRASAL VERBS - 30 questions
INSERT INTO public.grammarquestions (GrammarType, questiontext, optiona, optionb, optionc, optiond, correctoption) VALUES
('Phrasal Verbs', 'Please _____ the light. It''s dark.', 'turn on', 'turn off', 'turn up', 'turn down', 1),
('Phrasal Verbs', 'I need to _____ this form.', 'fill in', 'fill out', 'fill up', 'both a and b', 4),
('Phrasal Verbs', 'She _____ her mother very much.', 'looks after', 'looks like', 'looks for', 'looks up', 2),
('Phrasal Verbs', 'The meeting was _____ until next week.', 'called off', 'put off', 'taken off', 'both a and b', 4),
('Phrasal Verbs', 'I can''t _____ with this noise anymore.', 'put up', 'put up with', 'put on', 'put off', 2),
('Phrasal Verbs', 'He _____ a great idea.', 'came up with', 'came across', 'came out', 'came into', 1),
('Phrasal Verbs', 'She _____ her grandmother after school.', 'looks after', 'looks for', 'looks up', 'looks at', 1),
('Phrasal Verbs', 'The plane will _____ at 6 PM.', 'take off', 'take on', 'take over', 'take in', 1),
('Phrasal Verbs', 'I need to _____ the word in a dictionary.', 'look up', 'look for', 'look after', 'look into', 1),
('Phrasal Verbs', 'He _____ his father''s business.', 'took over', 'took off', 'took up', 'took in', 1),
('Phrasal Verbs', 'She _____ her keys.', 'looked for', 'looked after', 'looked up', 'looked into', 1),
('Phrasal Verbs', 'The fire _____ quickly.', 'spread out', 'spread over', 'spread to', 'spread through', 1),
('Phrasal Verbs', 'I _____ an old friend yesterday.', 'came across', 'came up with', 'came into', 'came out', 1),
('Phrasal Verbs', 'Please _____ your shoes before entering.', 'take off', 'take on', 'take up', 'take over', 1),
('Phrasal Verbs', 'She _____ smoking last year.', 'gave up', 'gave in', 'gave out', 'gave away', 1),
('Phrasal Verbs', 'We need to _____ a solution.', 'come up with', 'come across', 'come out', 'come in', 1),
('Phrasal Verbs', 'He _____ his boss for a raise.', 'asked for', 'asked about', 'asked after', 'asked around', 1),
('Phrasal Verbs', 'The car _____ gas on the highway.', 'ran out of', 'ran into', 'ran over', 'ran after', 1),
('Phrasal Verbs', 'She _____ her little sister while her parents were away.', 'looked after', 'looked for', 'looked up', 'looked into', 1),
('Phrasal Verbs', 'I can''t _____ the idea of moving.', 'get used to', 'get over', 'get through', 'get along', 1),
('Phrasal Verbs', 'He _____ the invitation.', 'turned down', 'turned up', 'turned on', 'turned off', 1),
('Phrasal Verbs', 'They _____ for the weekend.', 'went away', 'went on', 'went out', 'went over', 1),
('Phrasal Verbs', 'The meeting _____ at 10 AM.', 'starts off', 'starts up', 'starts out', 'starts over', 1),
('Phrasal Verbs', 'She _____ a new hobby.', 'took up', 'took in', 'took over', 'took off', 1),
('Phrasal Verbs', 'We need to _____ this problem.', 'sort out', 'sort through', 'sort after', 'sort over', 1),
('Phrasal Verbs', 'He _____ his success to hard work.', 'owes', 'attributes', 'credits', 'gives', 1),
('Phrasal Verbs', 'The price of oil has _____ .', 'gone up', 'gone down', 'gone over', 'gone through', 1),
('Phrasal Verbs', 'She _____ her feelings easily.', 'shows off', 'shows up', 'shows through', 'shows around', 1),
('Phrasal Verbs', 'I _____ the news on TV.', 'heard about', 'heard from', 'heard of', 'heard out', 1),
('Phrasal Verbs', 'They _____ their wedding because of the pandemic.', 'called off', 'put off', 'both a and b', 'called out', 3);

-- 16. RELATIVE CLAUSES - 30 questions
INSERT INTO public.grammarquestions (GrammarType, questiontext, optiona, optionb, optionc, optiond, correctoption) VALUES
('Relative Clauses', 'The man _____ is standing there is my uncle.', 'who', 'whom', 'which', 'whose', 1),
('Relative Clauses', 'The book _____ I read was interesting.', 'who', 'whom', 'which', 'whose', 3),
('Relative Clauses', 'This is the house _____ I grew up.', 'where', 'which', 'when', 'who', 1),
('Relative Clauses', 'She is the woman _____ car was stolen.', 'who', 'whom', 'whose', 'which', 3),
('Relative Clauses', 'The movie _____ we watched was great.', 'who', 'whom', 'which', 'whose', 3),
('Relative Clauses', 'I remember the day _____ we first met.', 'when', 'where', 'which', 'who', 1),
('Relative Clauses', 'The person _____ you called is not here.', 'who', 'whom', 'which', 'whose', 2),
('Relative Clauses', 'This is the reason _____ I left.', 'why', 'when', 'where', 'which', 1),
('Relative Clauses', 'The teacher _____ taught me is retiring.', 'who', 'whom', 'which', 'whose', 1),
('Relative Clauses', 'The restaurant _____ we ate was expensive.', 'where', 'when', 'which', 'who', 1),
('Relative Clauses', 'She is the girl _____ brother is a doctor.', 'who', 'whom', 'whose', 'which', 3),
('Relative Clauses', 'The car _____ is parked outside is mine.', 'who', 'whom', 'which', 'whose', 3),
('Relative Clauses', 'That''s the man _____ I gave the money.', 'who', 'whom', 'which', 'whose', 2),
('Relative Clauses', 'I''ll never forget the time _____ we went to Paris.', 'when', 'where', 'which', 'why', 1),
('Relative Clauses', 'This is the school _____ I studied.', 'where', 'when', 'which', 'who', 1),
('Relative Clauses', 'Anyone _____ makes noise will be punished.', 'who', 'whom', 'which', 'whose', 1),
('Relative Clauses', 'The cake _____ she made was delicious.', 'who', 'whom', 'which', 'whose', 3),
('Relative Clauses', 'That''s the dog _____ bit me.', 'who', 'whom', 'which', 'whose', 3),
('Relative Clauses', 'He is the man _____ we were talking about.', 'who', 'whom', 'which', 'whose', 2),
('Relative Clauses', 'This is the place _____ we first met.', 'where', 'when', 'which', 'why', 1),
('Relative Clauses', 'The people _____ live next door are friendly.', 'who', 'whom', 'which', 'whose', 1),
('Relative Clauses', 'I have a friend _____ father is a pilot.', 'who', 'whom', 'whose', 'which', 3),
('Relative Clauses', 'The laptop _____ I bought is broken.', 'who', 'whom', 'which', 'whose', 3),
('Relative Clauses', 'That''s the reason _____ I came late.', 'why', 'when', 'where', 'which', 1),
('Relative Clauses', 'The artist _____ painted this is famous.', 'who', 'whom', 'which', 'whose', 1),
('Relative Clauses', 'The city _____ I was born is beautiful.', 'where', 'when', 'which', 'why', 1),
('Relative Clauses', 'She is the one _____ won the lottery.', 'who', 'whom', 'which', 'whose', 1),
('Relative Clauses', 'The phone _____ I lost was expensive.', 'who', 'whom', 'which', 'whose', 3),
('Relative Clauses', 'That''s the moment _____ everything changed.', 'when', 'where', 'which', 'why', 1),
('Relative Clauses', 'The man with _____ I spoke was kind.', 'who', 'whom', 'which', 'whose', 2);

-- 17. NEGATION - 30 questions
INSERT INTO public.grammarquestions (GrammarType, questiontext, optiona, optionb, optionc, optiond, correctoption) VALUES
('Negation', 'I _____ like coffee.', 'don''t', 'doesn''t', 'am not', 'is not', 1),
('Negation', 'She _____ speak French.', 'don''t', 'doesn''t', 'isn''t', 'aren''t', 2),
('Negation', 'They _____ at home yesterday.', 'weren''t', 'wasn''t', 'didn''t', 'don''t', 1),
('Negation', 'He _____ finished his homework yet.', 'hasn''t', 'haven''t', 'isn''t', 'aren''t', 1),
('Negation', 'There _____ any milk left.', 'isn''t', 'aren''t', 'wasn''t', 'weren''t', 1),
('Negation', 'I _____ see you there.', 'couldn''t', 'can''t', 'may not', 'all of the above', 4),
('Negation', 'She _____ to the party.', 'didn''t come', 'doesn''t come', 'hasn''t come', 'all of the above', 4),
('Negation', 'He _____ happy with the results.', 'isn''t', 'aren''t', 'wasn''t', 'both a and c', 4),
('Negation', 'We _____ going to the beach tomorrow.', 'aren''t', 'isn''t', 'don''t', 'doesn''t', 1),
('Negation', 'She _____ eat meat.', 'doesn''t', 'don''t', 'isn''t', 'aren''t', 1),
('Negation', 'I _____ be late for the meeting.', 'won''t', 'wouldn''t', 'shan''t', 'all of the above', 4),
('Negation', 'They _____ to the museum last week.', 'didn''t go', 'haven''t gone', 'weren''t go', 'don''t go', 1),
('Negation', '_____ you like to come with us?', 'Wouldn''t', 'Don''t', 'Didn''t', 'Haven''t', 1),
('Negation', 'I have _____ seen him.', 'never', 'not', 'no', 'none', 1),
('Negation', 'She said _____ about it.', 'nothing', 'anything', 'something', 'everything', 1),
('Negation', '_____ of the answers was correct.', 'None', 'Neither', 'Either', 'Both', 2),
('Negation', 'He _____ to do it.', 'doesn''t want', 'don''t want', 'isn''t want', 'aren''t want', 1),
('Negation', 'They _____ living here anymore.', 'aren''t', 'isn''t', 'don''t', 'doesn''t', 1),
('Negation', 'I can _____ hear you.', 'hardly', 'not', 'no', 'never', 1),
('Negation', 'She _____ him.', 'didn''t recognize', 'doesn''t recognize', 'hasn''t recognized', 'all of the above', 4),
('Negation', '_____ speak to me like that!', 'Don''t', 'Doesn''t', 'Isn''t', 'Aren''t', 1),
('Negation', 'There _____ any students in the room.', 'aren''t', 'isn''t', 'wasn''t', 'hasn''t', 1),
('Negation', 'I _____ understand what you mean.', 'don''t', 'doesn''t', 'am not', 'is not', 1),
('Negation', 'She _____ going to change her mind.', 'isn''t', 'aren''t', 'don''t', 'doesn''t', 1),
('Negation', 'We _____ seen that movie.', 'haven''t', 'hasn''t', 'didn''t', 'weren''t', 1),
('Negation', 'He _____ drive a car.', 'can''t', 'couldn''t', 'may not', 'all of the above', 4),
('Negation', '_____ you finish the project?', 'Didn''t', 'Don''t', 'Doesn''t', 'Isn''t', 1),
('Negation', 'I have _____ money left.', 'no', 'not', 'none', 'any', 1),
('Negation', 'She is _____ interested in sports.', 'not', 'no', 'none', 'never', 1),
('Negation', 'They _____ to the concert last night.', 'didn''t go', 'haven''t gone', 'weren''t go', 'don''t go', 1);

-- 18. CAUSATIVES - 20 questions (since 30 may be excessive for this topic)
INSERT INTO public.grammarquestions (GrammarType, questiontext, optiona, optionb, optionc, optiond, correctoption) VALUES
('Causatives', 'I _____ my hair cut yesterday.', 'had', 'got', 'made', 'both a and b', 4),
('Causatives', 'She _____ her car washed every week.', 'has', 'gets', 'makes', 'both a and b', 4),
('Causatives', 'They _____ their house painted last year.', 'had', 'got', 'made', 'both a and b', 4),
('Causatives', 'He _____ his assistant type the report.', 'had', 'got', 'made', 'let', 3),
('Causatives', 'I will _____ my shoes repaired.', 'have', 'get', 'make', 'both a and b', 4),
('Causatives', 'She _____ her children do their homework.', 'makes', 'has', 'gets', 'lets', 1),
('Causatives', 'They _____ the roof fixed after the storm.', 'had', 'got', 'made', 'both a and b', 4),
('Causatives', 'He _____ his secretary call me.', 'had', 'got', 'made', 'both a and c', 4),
('Causatives', 'I _____ my dress altered for the wedding.', 'had', 'got', 'made', 'both a and b', 4),
('Causatives', 'She _____ her brother carry the bags.', 'had', 'made', 'got', 'let', 2),
('Causatives', 'We _____ the grass cut yesterday.', 'had', 'got', 'made', 'both a and b', 4),
('Causatives', 'He _____ his car fixed at the garage.', 'had', 'got', 'made', 'both a and b', 4),
('Causatives', 'The teacher _____ the students stay after class.', 'made', 'had', 'got', 'let', 1),
('Causatives', 'I _____ my room painted blue.', 'had', 'got', 'made', 'both a and b', 4),
('Causatives', 'She _____ her hair done for the party.', 'had', 'got', 'made', 'both a and b', 4),
('Causatives', 'They _____ the project completed on time.', 'had', 'got', 'made', 'both a and b', 4),
('Causatives', 'He _____ his employees work overtime.', 'made', 'had', 'got', 'let', 1),
('Causatives', 'I _____ my watch repaired at the jewelry store.', 'had', 'got', 'made', 'both a and b', 4),
('Causatives', 'She _____ her son clean his room.', 'made', 'had', 'got', 'let', 1),
('Causatives', 'We _____ our photo taken at the studio.', 'had', 'got', 'made', 'both a and b', 4);

-- 19. INVERSIONS - 20 questions
INSERT INTO public.grammarquestions (GrammarType, questiontext, optiona, optionb, optionc, optiond, correctoption) VALUES
('Inversions', 'Never _____ I seen such a beautiful sunset.', 'have', 'has', 'had', 'did', 1),
('Inversions', 'Not only _____ she late, but she also forgot her keys.', 'was', 'is', 'were', 'are', 1),
('Inversions', 'Seldom _____ they visit us.', 'do', 'does', 'did', 'have', 1),
('Inversions', 'Only after the movie _____ we go home.', 'did', 'do', 'does', 'had', 1),
('Inversions', 'Hardly _____ I arrived when the phone rang.', 'had', 'have', 'has', 'did', 1),
('Inversions', 'No sooner _____ he left than it started to rain.', 'had', 'has', 'have', 'did', 1),
('Inversions', 'Under no circumstances _____ you tell anyone.', 'should', 'shall', 'will', 'must', 1),
('Inversions', 'Not until I saw it _____ I believe it.', 'did', 'do', 'does', 'had', 1),
('Inversions', 'Rarely _____ she eat out.', 'does', 'do', 'did', 'has', 1),
('Inversions', 'Only then _____ I understand the truth.', 'did', 'do', 'does', 'had', 1),
('Inversions', 'In no way _____ this be allowed.', 'should', 'shall', 'must', 'can', 1),
('Inversions', 'Never before _____ I seen such talent.', 'have', 'has', 'had', 'did', 1),
('Inversions', 'Not only _____ he speak English, but he also speaks French.', 'does', 'do', 'did', 'has', 1),
('Inversions', 'Little _____ she know what was coming.', 'did', 'does', 'do', 'had', 1),
('Inversions', 'So beautiful _____ the painting that everyone stopped to look.', 'was', 'is', 'were', 'are', 1),
('Inversions', 'Such _____ his anger that nobody dared speak.', 'was', 'is', 'were', 'are', 1),
('Inversions', 'On no account _____ you leave the door unlocked.', 'should', 'shall', 'must', 'can', 1),
('Inversions', 'Nowhere _____ I find such peace.', 'can', 'could', 'will', 'would', 1),
('Inversions', 'Only by working hard _____ you succeed.', 'will', 'can', 'may', 'shall', 1),
('Inversions', 'Had I known, I _____ come earlier.', 'would have', 'will have', 'have', 'had', 1);

-- 20. DIRECT AND INDIRECT OBJECTS - 20 questions
INSERT INTO public.grammarquestions (GrammarType, questiontext, optiona, optionb, optionc, optiond, correctoption) VALUES
('Direct Indirect Objects', 'She gave _____ a gift.', 'me', 'I', 'my', 'mine', 1),
('Direct Indirect Objects', 'He sent _____ a letter.', 'her', 'she', 'hers', 'herself', 1),
('Direct Indirect Objects', 'I bought _____ a new phone.', 'him', 'he', 'his', 'himself', 1),
('Direct Indirect Objects', 'She told _____ the truth.', 'us', 'we', 'our', 'ours', 1),
('Direct Indirect Objects', 'He showed _____ his car.', 'them', 'they', 'their', 'theirs', 1),
('Direct Indirect Objects', 'I gave _____ some advice.', 'her', 'she', 'hers', 'herself', 1),
('Direct Indirect Objects', 'She made _____ a cake.', 'me', 'I', 'my', 'mine', 1),
('Direct Indirect Objects', 'He taught _____ French.', 'us', 'we', 'our', 'ours', 1),
('Direct Indirect Objects', 'They offered _____ a job.', 'him', 'he', 'his', 'himself', 1),
('Direct Indirect Objects', 'I wrote _____ a letter.', 'her', 'she', 'hers', 'herself', 1),
('Direct Indirect Objects', 'She cooked _____ dinner.', 'them', 'they', 'their', 'theirs', 1),
('Direct Indirect Objects', 'He lent _____ some money.', 'me', 'I', 'my', 'mine', 1),
('Direct Indirect Objects', 'I promised _____ a surprise.', 'her', 'she', 'hers', 'herself', 1),
('Direct Indirect Objects', 'She read _____ a story.', 'us', 'we', 'our', 'ours', 1),
('Direct Indirect Objects', 'He threw _____ the ball.', 'me', 'I', 'my', 'mine', 1),
('Direct Indirect Objects', 'They wished _____ good luck.', 'us', 'we', 'our', 'ours', 1),
('Direct Indirect Objects', 'I handed _____ the keys.', 'him', 'he', 'his', 'himself', 1),
('Direct Indirect Objects', 'She bought _____ a present.', 'me', 'I', 'my', 'mine', 1),
('Direct Indirect Objects', 'He told _____ a joke.', 'us', 'we', 'our', 'ours', 1),
('Direct Indirect Objects', 'They sent _____ an invitation.', 'her', 'she', 'hers', 'herself', 1);

-- 21. EMBEDDED QUESTIONS - 20 questions
INSERT INTO public.grammarquestions (GrammarType, questiontext, optiona, optionb, optionc, optiond, correctoption) VALUES
('Embedded Questions', 'Could you tell me where _____ ?', 'the station is', 'is the station', 'the station', 'does the station', 1),
('Embedded Questions', 'I wonder what _____ .', 'she wants', 'does she want', 'she want', 'wants she', 1),
('Embedded Questions', 'Do you know when _____ ?', 'they will arrive', 'will they arrive', 'they arrive', 'do they arrive', 1),
('Embedded Questions', 'I don''t know why _____ .', 'she left', 'did she leave', 'she leave', 'left she', 1),
('Embedded Questions', 'Can you tell me how _____ to the airport?', 'to get', 'get', 'getting', 'got', 1),
('Embedded Questions', 'I''m not sure if _____ .', 'he is coming', 'is he coming', 'he coming', 'does he come', 1),
('Embedded Questions', 'She asked whether _____ the job.', 'I wanted', 'did I want', 'I want', 'want I', 1),
('Embedded Questions', 'I wonder how much _____ .', 'it costs', 'does it cost', 'it cost', 'costs it', 1),
('Embedded Questions', 'Do you know who _____ ?', 'she is', 'is she', 'she', 'her', 1),
('Embedded Questions', 'I don''t remember where _____ .', 'I put it', 'did I put it', 'I put', 'put I', 1),
('Embedded Questions', 'Can you tell me what time _____ ?', 'it is', 'is it', 'it', 'its', 1),
('Embedded Questions', 'I''d like to know how long _____ .', 'it takes', 'does it take', 'it take', 'takes it', 1),
('Embedded Questions', 'He wants to know why _____ .', 'you called', 'did you call', 'you call', 'call you', 1),
('Embedded Questions', 'Do you know which one _____ ?', 'he chose', 'did he choose', 'he choose', 'chooses he', 1),
('Embedded Questions', 'I''m not sure where _____ .', 'to go', 'go', 'going', 'went', 1),
('Embedded Questions', 'She asked how old _____ .', 'I was', 'was I', 'I am', 'am I', 1),
('Embedded Questions', 'I wonder if _____ me.', 'you can help', 'can you help', 'you help', 'help you', 1),
('Embedded Questions', 'Do you know whose _____ ?', 'this is', 'is this', 'this', 'it is', 1),
('Embedded Questions', 'I don''t understand what _____ .', 'you mean', 'do you mean', 'you means', 'mean you', 1),
('Embedded Questions', 'Can you tell me how often _____ ?', 'you exercise', 'do you exercise', 'you exercising', 'exercise you', 1);

-- 22. COLLOCATIONS - 20 questions
INSERT INTO public.grammarquestions (GrammarType, questiontext, optiona, optionb, optionc, optiond, correctoption) VALUES
('Collocations', 'She _____ a lot of money on clothes.', 'spends', 'takes', 'costs', 'pays', 1),
('Collocations', 'He _____ a mistake in the calculation.', 'made', 'did', 'took', 'had', 1),
('Collocations', 'I _____ attention to what he said.', 'paid', 'gave', 'took', 'made', 1),
('Collocations', 'She _____ a promise to help me.', 'made', 'did', 'took', 'gave', 1),
('Collocations', 'He _____ a decision to quit his job.', 'made', 'did', 'took', 'had', 1),
('Collocations', 'I _____ business with him for years.', 'do', 'make', 'take', 'have', 1),
('Collocations', 'She _____ a favor for her friend.', 'did', 'made', 'took', 'gave', 1),
('Collocations', 'He _____ a good impression on everyone.', 'made', 'did', 'took', 'gave', 1),
('Collocations', 'I _____ time to finish the project.', 'took', 'made', 'did', 'spent', 1),
('Collocations', 'She _____ responsibility for the accident.', 'took', 'made', 'did', 'had', 1),
('Collocations', 'He _____ an effort to learn Spanish.', 'made', 'did', 'took', 'gave', 1),
('Collocations', 'I _____ a chance and applied for the job.', 'took', 'made', 'did', 'gave', 1),
('Collocations', 'She _____ a call to her mother.', 'made', 'did', 'took', 'gave', 1),
('Collocations', 'He _____ a complaint about the service.', 'made', 'did', 'took', 'gave', 1),
('Collocations', 'I _____ a suggestion at the meeting.', 'made', 'did', 'took', 'gave', 1),
('Collocations', 'She _____ a course in photography.', 'took', 'made', 'did', 'had', 1),
('Collocations', 'He _____ a shower before breakfast.', 'took', 'made', 'did', 'had', 1),
('Collocations', 'I _____ a break after working for hours.', 'took', 'made', 'did', 'had', 1),
('Collocations', 'She _____ a photo of the sunset.', 'took', 'made', 'did', 'had', 1),
('Collocations', 'He _____ a trip to Europe last summer.', 'took', 'made', 'did', 'had', 1);

-- 23. IDIOMS - 20 questions
INSERT INTO public.grammarquestions (GrammarType, questiontext, optiona, optionb, optionc, optiond, correctoption) VALUES
('Idioms', 'It''s raining _____ .', 'cats and dogs', 'horses and cows', 'pigs and chickens', 'birds and bees', 1),
('Idioms', 'He is feeling under the _____ .', 'weather', 'water', 'cloud', 'rain', 1),
('Idioms', 'Break a _____ ! (Good luck)', 'leg', 'arm', 'foot', 'hand', 1),
('Idioms', 'She let the cat out of the _____ .', 'bag', 'box', 'house', 'car', 1),
('Idioms', 'He is a _____ in the neck.', 'pain', 'ache', 'hurt', 'sore', 1),
('Idioms', 'Don''t beat around the _____ .', 'bush', 'tree', 'plant', 'flower', 1),
('Idioms', 'She has a _____ of gold.', 'heart', 'soul', 'mind', 'spirit', 1),
('Idioms', 'It''s a piece of _____ .', 'cake', 'pie', 'bread', 'candy', 1),
('Idioms', 'He bit off more than he could _____ .', 'chew', 'eat', 'swallow', 'bite', 1),
('Idioms', 'She is on cloud _____ .', 'nine', 'seven', 'ten', 'eight', 1),
('Idioms', 'Let''s call it a _____ .', 'day', 'night', 'time', 'moment', 1),
('Idioms', 'He spilled the _____ .', 'beans', 'water', 'milk', 'juice', 1),
('Idioms', 'She hit the _____ on the head.', 'nail', 'hammer', 'screw', 'bolt', 1),
('Idioms', 'It cost an arm and a _____ .', 'leg', 'foot', 'hand', 'head', 1),
('Idioms', 'He is all _____ .', 'ears', 'eyes', 'hands', 'feet', 1),
('Idioms', 'She has a _____ memory.', 'photographic', 'picture', 'photo', 'camera', 1),
('Idioms', 'He is a _____ potato.', 'couch', 'sofa', 'chair', 'bed', 1),
('Idioms', 'She wears her _____ on her sleeve.', 'heart', 'soul', 'mind', 'feelings', 1),
('Idioms', 'It''s not rocket _____ .', 'science', 'surgery', 'engineering', 'physics', 1),
('Idioms', 'He kicked the _____ .', 'bucket', 'ball', 'can', 'box', 1);

-- 24. HOMOPHONES - 20 questions
INSERT INTO public.grammarquestions (GrammarType, questiontext, optiona, optionb, optionc, optiond, correctoption) VALUES
('Homophones', 'She _____ her keys on the table.', 'left', 'left', 'left', 'left', 1),
('Homophones', 'I need to _____ a letter.', 'write', 'right', 'rite', 'wright', 1),
('Homophones', 'He _____ the race yesterday.', 'won', 'one', 'wan', 'wun', 1),
('Homophones', 'They are _____ there.', 'their', 'there', 'they''re', 'thair', 2),
('Homophones', '_____ going to the party tonight.', 'Their', 'There', 'They''re', 'Thair', 3),
('Homophones', 'That is _____ car.', 'their', 'there', 'they''re', 'thair', 1),
('Homophones', 'I can''t _____ the difference.', 'see', 'sea', 'se', 'cee', 1),
('Homophones', 'Let''s go to the _____ .', 'beach', 'beech', 'bech', 'beache', 1),
('Homophones', 'He is a _____ man.', 'fair', 'fare', 'fayre', 'fear', 1),
('Homophones', 'She has _____ hair.', 'fair', 'fare', 'fayre', 'fear', 1),
('Homophones', 'The bus _____ is expensive.', 'fair', 'fare', 'fayre', 'fear', 2),
('Homophones', 'I _____ you yesterday.', 'saw', 'sore', 'saur', 'sawr', 1),
('Homophones', 'My throat is _____ .', 'saw', 'sore', 'saur', 'sawr', 2),
('Homophones', 'He is my _____ .', 'son', 'sun', 'sunn', 'sone', 1),
('Homophones', 'The _____ is shining brightly.', 'son', 'sun', 'sunn', 'sone', 2),
('Homophones', 'She _____ to be a doctor.', 'wants', 'wonts', 'wons', 'wants', 1),
('Homophones', 'I _____ to go home.', 'want', 'wont', 'wont', 'wonte', 1),
('Homophones', 'He _____ a new car.', 'bought', 'bote', 'baught', 'bought', 1),
('Homophones', 'She _____ me a gift.', 'gave', 'gav', 'gove', 'gave', 1),
('Homophones', 'I have _____ books.', 'eight', 'ate', 'ait', 'eit', 1);

-- 25. COMMON MISTAKES - 20 questions
INSERT INTO public.grammarquestions (GrammarType, questiontext, optiona, optionb, optionc, optiond, correctoption) VALUES
('Common Mistakes', 'I could _____ swim when I was five.', 'already', 'already', 'already', 'already', 1),
('Common Mistakes', 'She is _____ than her sister.', 'older', 'elder', 'old', 'more old', 1),
('Common Mistakes', 'He is the _____ of the two brothers.', 'older', 'elder', 'oldest', 'most old', 2),
('Common Mistakes', 'I _____ you yesterday.', 'called', 'call', 'have called', 'was call', 1),
('Common Mistakes', 'She _____ to the store every day.', 'goes', 'go', 'is going', 'went', 1),
('Common Mistakes', 'They _____ playing football now.', 'are', 'is', 'am', 'be', 1),
('Common Mistakes', 'I have _____ finished my homework.', 'already', 'yet', 'still', 'just', 1),
('Common Mistakes', 'She hasn''t arrived _____ .', 'yet', 'already', 'still', 'just', 1),
('Common Mistakes', 'He _____ to work yesterday.', 'didn''t go', 'didn''t went', 'didn''t gone', 'not went', 1),
('Common Mistakes', 'I am looking forward _____ you.', 'to seeing', 'to see', 'for seeing', 'for see', 1),
('Common Mistakes', 'She is used _____ up early.', 'to waking', 'to wake', 'waking', 'wake', 1),
('Common Mistakes', 'I would rather _____ at home.', 'stay', 'to stay', 'staying', 'stayed', 1),
('Common Mistakes', 'He suggested _____ to the beach.', 'going', 'to go', 'go', 'went', 1),
('Common Mistakes', 'I wish I _____ taller.', 'were', 'was', 'am', 'is', 1),
('Common Mistakes', 'If I _____ you, I would go.', 'were', 'was', 'am', 'is', 1),
('Common Mistakes', 'She asked me where _____ .', 'I lived', 'did I live', 'I live', 'live I', 1),
('Common Mistakes', 'The reason _____ he was late is traffic.', 'why', 'that', 'because', 'for', 1),
('Common Mistakes', 'I have _____ money.', 'no', 'not', 'none', 'any', 1),
('Common Mistakes', 'She can _____ speak English.', 'also', 'too', 'as well', 'either', 1),
('Common Mistakes', 'I like coffee, and I like tea _____.', 'too', 'also', 'as well', 'either', 1);